coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
    patch:
      default:
        target: auto
        threshold: 0%

ignore:
  - "parser/parser.go"
  - "**/*_test.go"
  - "testutil/**"
