name: docker
on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

jobs:
  build:
    name: ${{ startsWith(github.ref, 'refs/tags/') && 'push' || 'build' }} (${{ matrix.cmd }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmd: [mysqldef, sqlite3def, mssqldef, psqldef]
    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Log in to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: sqldef
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: sqldef/${{ matrix.cmd }}
          tags: |
              type=ref,event=branch
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}

      - name: ${{ startsWith(github.ref, 'refs/tags/') && 'Push' || 'Build' }} Docker image
        id: push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: SQLDEF_TOOL=${{ matrix.cmd }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.cmd }}
          cache-to: type=gha,scope=${{ matrix.cmd }},mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
        with:
          subject-name: index.docker.io/sqldef/${{ matrix.cmd }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
        if: ${{ startsWith(github.ref, 'refs/tags/') }}

  build-result:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: build jobs have failed
        run: exit 1
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
