name: tagpr
on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  tagpr:
    runs-on: ubuntu-slim
    steps:
    - name: Generate token
      id: generate_token
      uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
      with:
        app-id: ${{ secrets.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
        permission-contents: write
        permission-pull-requests: write

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        token: ${{ steps.generate_token.outputs.token }}

    - uses: Songmu/tagpr@e7ae290f5cc5faabfdb4d131f8e4ce073ad8b3e2 # v1.18.0
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
